kay_blog_post:
    resource: "@KayBlogBundle/Resources/config/routing/Post.yml"
    prefix:   /post

kay_blog_user:
    resource: "@KayBlogBundle/Resources/config/routing/user.yml"
    prefix:   /user