kay_user:
    resource: "@KayUserBundle/Resources/config/routing.yml"
    prefix:   /

kay_blog:
    resource: "@KayBlogBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: KayUserBundle:Security:login }

logout:
    path:     /logout
